export const POINT = {
  FULL_DOT: 0,
  CROSS: 1,
  EMPTY_DOT: 2,
  PLUS_SIGN: 3,
  FULL_DIAMOND: 4,
  EMPTY_DIAMOND: 5,
  TRIANGLE_NORTH: 6,
  TRIANGLE_SOUTH: 7,
  TRIANGLE_EAST: 8,
  TRIANGLE_WEST: 9,
  FULL_DOT_NO_OUTLINE: 10
}
