export const ADD_ELEMENT_TO_STORE = 'ADD_ELEMENT_TO_STORE'
export const UPDATE_ELEMENT_IN_STORE = 'UPDATE_ELEMENT_IN_STORE'
export const REMOVE_ELEMENT_FROM_STORE = 'REMOVE_ELEMENT_FROM_STORE'
export const RENAME_ELEMENT_IN_STORE = 'RENAME_ELEMENT_IN_STORE'

export const ADD_NAME_TO_SELECTED_ELEMENTS = 'ADD_NAME_TO_SELECTED_ELEMENTS'
export const REMOVE_ELEMENTS_AT_CANCEL = 'REMOVE_ELEMENTS_AT_CANCEL'
export const REMOVE_NAME_FROM_SELECTED_ELEMENTS =
  'REMOVE_NAME_FROM_SELECTED_ELEMENTS'
export const SET_MODE_IN_STORE = 'SET_MODE_IN_STORE'
export const SET_PERSPECTIVE_IN_STORE = 'SET_PERSPECTIVE_IN_STORE'

export const SET_MOUSEDOWN_IN_STORE = 'SET_MOUSEDOWN_IN_STORE'

export const SET_EUCLIDIANVIEWS_IN_STORE = 'SET_EUCLIDIANVIEWS_IN_STORE'
export const SET_EUCLIDIANVIEW3D_IN_STORE = 'SET_EUCLIDIANVIEW3D_IN_STORE'

//export const RESET_SELECTED_ELEMENTS = 'RESET_SELECTED_ELEMENTS'
export const ON_APPLET_LOADED = 'ON_APPLET_LOADED'
export const SET_ON_CONNECT = 'SET_ON_CONNECT'
